- name: remove sid debian repo
  apt_repository:
    repo: deb http://ftp.ca.debian.org/debian sid main
    state: absent

- name: remove systemd unit override files
  file:
    state: "{{ item }}"
    path: "/etc/systemd/system/etcd.service.d/"
  with_items:
    - absent

- name: remove etcd
  apt:
    name: etcd
    state: absent
    autoremove: yes
    purge: yes
