- name: install dnsmasq and resolvconf
  apt: pkg={{ item }} state=installed
  with_items:
    - dnsmasq
    - resolvconf
    - dnsutils

- name: Setup dnsmasq host records
  template: src=cluster.hosts.conf dest=/etc/dnsmasq.d/cluster.hosts.conf
  notify: "restart dnsmasq"

- meta: flush_handlers
