---
- name: Gather details
  hosts: all
  remote_user: pirate
  tasks: []

- name: Prepare cluster apt cache
  hosts: local_repo
  gather_facts: no
  remote_user: pirate
  become: true
  become_method: sudo

  roles:
    - apt-cacher-ng

- name: Prepate cluster dns
  hosts: all
  gather_facts: no
  remote_user: pirate
  become: true
  become_method: sudo

  roles:
    - dnsmasq
